### ISSUE TITLE
MSBuild Scanner Not Found (SonarQube.MSBuild.Runner.Implementation.zip)

### ISSUE THREAD

**Issue by jorymorrison** [SonarSource/sonar-dotnet#2444]
### Description

When performing the Fetch Quality Profile from Sonarqube step in Azure Devops I encounter the following error:
```
2019-06-06T17:33:36.9960710Z ##[section]Starting: [DEPRECATED] Fetch the Quality Profile from SonarQube
2019-06-06T17:33:36.9969603Z ==============================================================================
2019-06-06T17:33:36.9969677Z Task         : SonarQube for MSBuild - Begin Analysis
2019-06-06T17:33:36.9969731Z Description  : [DEPRECATED] Fetch the Quality Profile from SonarQube to configure the analysis
2019-06-06T17:33:36.9969786Z Version      : 1.0.50
2019-06-06T17:33:36.9969830Z Author       : Microsoft Corporation
2019-06-06T17:33:36.9969880Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkId=620063)
2019-06-06T17:33:36.9969937Z ==============================================================================
2019-06-06T17:33:37.0182306Z Preparing task execution handler.
2019-06-06T17:33:40.2707353Z Executing the powershell script: C:\agent-64\_work\_tasks\SonarQubePreBuild_eae5b2cc-ac5e-4cba-b022-a06621f9c01f\1.0.50\SonarQubePreBuild.ps1
2019-06-06T17:33:40.5882222Z ##[warning] The ownership of the SonarQube related build tasks is being transferred to SonarSource.
2019-06-06T17:33:40.5896346Z ##[warning] Please replace this build task with the one brought by SonarSource's extension on the marketplace: https://aka.ms/sqextension
2019-06-06T17:33:40.5896777Z ##[warning] For more details go to https://aka.ms/sqtransfer
2019-06-06T17:33:40.7155424Z 
2019-06-06T17:33:40.7155524Z 
2019-06-06T17:33:40.7155710Z 
2019-06-06T17:33:40.7155742Z 
2019-06-06T17:33:40.7174503Z 
2019-06-06T17:33:40.7174722Z 
2019-06-06T17:33:40.7179659Z 
2019-06-06T17:33:40.7179736Z 
2019-06-06T17:33:40.7184715Z 
2019-06-06T17:33:40.7184975Z 
2019-06-06T17:33:40.7192460Z 
2019-06-06T17:33:40.7192554Z 
2019-06-06T17:33:40.7198261Z 
2019-06-06T17:33:40.7198306Z 
2019-06-06T17:33:40.7287964Z 
2019-06-06T17:33:40.7288165Z 
2019-06-06T17:33:40.7291962Z 
2019-06-06T17:33:40.7292013Z 
2019-06-06T17:33:40.7296792Z 
2019-06-06T17:33:40.7299167Z 
2019-06-06T17:33:40.7302136Z 
2019-06-06T17:33:40.7302183Z 
2019-06-06T17:33:41.2002974Z SonarQube Scanner for MSBuild 1.1
2019-06-06T17:33:41.3009276Z Default properties file was not found at C:\agent-64\_work\_tasks\SonarQubePreBuild_eae5b2cc-ac5e-4cba-b022-a06621f9c01f\1.0.50\SonarQube.Bootstrapper\SonarQube.Analysis.xml
2019-06-06T17:33:41.3009603Z Pre-processing started.
2019-06-06T17:33:41.3009744Z Preparing working directories...
2019-06-06T17:33:41.3009844Z Checking for updates...
2019-06-06T17:33:41.5028811Z ##[error]Could not find a file on the SonarQube server. Url: http://192.168.71.128:9000/static/csharp/SonarQube.MSBuild.Runner.Implementation.zip
2019-06-06T17:33:41.5029110Z ##[error]Failed to update the SonarQube Scanner for MSBuild binaries. Check the server url, verify that the C# plugin is correctly installed on the SonarQube server and that the SonarQube server has been restarted.
2019-06-06T17:33:41.5029199Z ##[error]Pre-processing failed. Exit code: 1
2019-06-06T17:33:41.5279676Z ##[error]System.Exception: Unexpected exit code received from batch file: 1
2019-06-06T17:33:41.5280091Z    at Microsoft.TeamFoundation.DistributedTask.Task.Internal.InvokeBatchScriptCmdlet.ProcessRecord()
2019-06-06T17:33:41.5280170Z    at System.Management.Automation.CommandProcessor.ProcessRecord()
2019-06-06T17:33:41.5639986Z ##[error]PowerShell script completed with 1 errors.
2019-06-06T17:33:41.5650873Z ##[section]Finishing: [DEPRECATED] Fetch the Quality Profile from SonarQube
```
### Repro steps

1. Install Azure Devops 17.143.28621.4

2. SonarSource extension version 4.6.3 installed

3. Sonarqube server configured as generic service

4. Sonar C# version 7.11 installed

5. SonarVB version 7.11 installed

### Expected behavior

The MSBuild executable is located and the quality profile is fetched.

### Actual behavior

I receive numerous warnings regarding deprecation of the Sonarsource plugin although I am running the latest version installed via instructions found at https://aka.ms/sqtransfer

I receive an error stating the MSBuild executable cannot be found on the Sonarqube server

### Known workarounds

None known

### Related information

Azure Devops 17.143.28621.4

SonarSource extension version 4.6.3 

Sonar C# version 7.11 installed

SonarVB version 7.11 installed

**Comment by andrei-epure-sonarsource** [comment]
Hi @jorymorrison. This repository contains the code for our analyzers.

For problems with the Azure Devops integration, please post on our https://community.sonarsource.com/ forum.
