### ISSUE TITLE
C# 7 tuples in foreach makes CFG creation fail

### ISSUE THREAD

**Issue by alban-auzeill** [SonarSource/sonar-dotnet#2675]
### Description

CSharpControlFlowGraphBuilder fails to create the CFG of tuples in `foreach`.

### Repro steps

Create the CFG of the following `Bar` method:
```cs
namespace NS
{
  public class Foo
  {
    public void Bar((string key, string value)[] bars)
    {
      foreach (var (key, value) in bars) { }
    }
  }
}
```

### Expected behavior

Should not throw an exception.

### Actual behavior

```
System.NotSupportedException: ForEachVariableStatement
  at SonarAnalyzer.ControlFlowGraph.CSharp.CSharpControlFlowGraphBuilder.BuildStatement(StatementSyntax statement, Block currentBlock) in sonaranalyzer-dotnet\src\SonarAnalyzer.CSharp\ControlFlowGraph\CSharpControlFlowGraphBuilder.cs:line 209
  at SonarAnalyzer.ControlFlowGraph.CSharp.CSharpControlFlowGraphBuilder.BuildStatements(IEnumerable`1 statements, Block currentBlock) in sonaranalyzer-dotnet\src\SonarAnalyzer.CSharp\ControlFlowGraph\CSharpControlFlowGraphBuilder.cs:line 486
  at SonarAnalyzer.ControlFlowGraph.CSharp.CSharpControlFlowGraphBuilder.BuildBlock(BlockSyntax block, Block currentBlock) in sonaranalyzer-dotnet\src\SonarAnalyzer.CSharp\ControlFlowGraph\CSharpControlFlowGraphBuilder.cs:line 975
  at SonarAnalyzer.ControlFlowGraph.CSharp.CSharpControlFlowGraphBuilder.BuildStatement(StatementSyntax statement, Block currentBlock) in sonaranalyzer-dotnet\src\SonarAnalyzer.CSharp\ControlFlowGraph\CSharpControlFlowGraphBuilder.cs:line 126
  at SonarAnalyzer.ControlFlowGraph.CSharp.CSharpControlFlowGraphBuilder.BuildStatements(IEnumerable`1 statements, Block currentBlock) in sonaranalyzer-dotnet\src\SonarAnalyzer.CSharp\ControlFlowGraph\CSharpControlFlowGraphBuilder.cs:line 486
  at SonarAnalyzer.ControlFlowGraph.CSharp.CSharpControlFlowGraphBuilder.BuildBlock(BlockSyntax block, Block currentBlock) in sonaranalyzer-dotnet\src\SonarAnalyzer.CSharp\ControlFlowGraph\CSharpControlFlowGraphBuilder.cs:line 975
  at SonarAnalyzer.ControlFlowGraph.CSharp.CSharpControlFlowGraphBuilder.BuildStatement(StatementSyntax statement, Block currentBlock) in sonaranalyzer-dotnet\src\SonarAnalyzer.CSharp\ControlFlowGraph\CSharpControlFlowGraphBuilder.cs:line 126
  at SonarAnalyzer.ControlFlowGraph.CSharp.CSharpControlFlowGraphBuilder.Build(SyntaxNode node, Block currentBlock) in sonaranalyzer-dotnet\src\SonarAnalyzer.CSharp\ControlFlowGraph\CSharpControlFlowGraphBuilder.cs:line 85
  at SonarAnalyzer.ControlFlowGraph.AbstractControlFlowGraphBuilder.Build() in sonaranalyzer-dotnet\src\SonarAnalyzer.Common\ControlFlowGraph\AbstractControlFlowGraphBuilder.cs:line 126
  at SonarAnalyzer.ControlFlowGraph.CSharp.CSharpControlFlowGraph.Create(CSharpSyntaxNode node, SemanticModel semanticModel) in sonaranalyzer-dotnet\src\SonarAnalyzer.CSharp\ControlFlowGraph\CSharpControlFlowGraph.cs:line 36
```

### Related information

Detected during #2541 
Related to #2681

**Comment by costin-zaharia-sonarsource** [comment]
This is no longer reproducible. It was fixed while adding support for C# 8 features (jira.sonarsource.com/browse/MMF-1808).
