### ISSUE TITLE
NoClassDefFoundErrorAbstractSensor

### ISSUE THREAD

**Issue by tools2devops** [SonarSource/sonar-dotnet#2787]
### Description

When we try to build a project and analysis this, we get the following exception to be thrown at the end of the sonar-scanner analysis _**:java.lang.NoClassDefFoundError: org/sonarsource/dotnet/shared/plugins/AbstractSensor**_

### Expected behavior

The analysis should succeed without an error.

### Actual behavior

ERROR: Error during SonarQube Scanner execution
	java.lang.NoClassDefFoundError: org/sonarsource/dotnet/shared/plugins/AbstractSensor
		at java.lang.ClassLoader.defineClass1(Native Method)
		at java.lang.ClassLoader.defineClass(Unknown Source)
		at java.security.SecureClassLoader.defineClass(Unknown Source)
		at java.net.URLClassLoader.defineClass(Unknown Source)
		at java.net.URLClassLoader.access$100(Unknown Source)
		at java.net.URLClassLoader$1.run(Unknown Source)
		at java.net.URLClassLoader$1.run(Unknown Source)
		at java.security.AccessController.doPrivileged(Native Method)
		at java.net.URLClassLoader.findClass(Unknown Source)
		at org.sonar.classloader.ClassRealm.loadClassFromSelf(ClassRealm.java:125)
		at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:37)
		at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
		at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
		at org.sonar.plugins.csharp.CSharpPlugin.define(CSharpPlugin.java:58)
		at org.sonar.scanner.bootstrap.ExtensionInstaller.install(ExtensionInstaller.java:55)
		at org.sonar.scanner.task.TaskContainer.addTaskExtensions(TaskContainer.java:62)
		at org.sonar.scanner.task.TaskContainer.doBeforeStart(TaskContainer.java:49)
		at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
		at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:129)
		at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:118)
		at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:117)
		at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:77)
		at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
		at java.lang.reflect.Method.invoke(Unknown Source)
		at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
		at com.sun.proxy.$Proxy0.execute(Unknown Source)
		at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:171)
		at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:128)
		at org.sonarsource.scanner.cli.Main.execute(Main.java:111)
		at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
		at org.sonarsource.scanner.cli.Main.main(Main.java:61)
	Caused by: java.lang.ClassNotFoundException: org.sonarsource.dotnet.shared.plugins.AbstractSensor
		at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:39)
		at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
		at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
		... 34 more

### Known workarounds

---

### Related information
* SonarQube Version 6.4 (build 25310)
* Dependency-Check 1.0.3 (dependencycheck)
* CSS / SCSS / Less 3.1 (css)
* SonarPython 1.8.0.1496 (python)
* SVN 1.5.0.715 (scmsvn)
* SonarJS 3.1.1.5128 (javascript)
* SonarC# 6.4.0.3347 (csharp)
* SonarJava 4.12.0.11033 (java)
* LDAP 2.2.0.608 (ldap)
* Flex 2.3 (flex)
* Git 1.2 (scmgit)
* SonarXML 1.4.3.1027 (xml)
* SonarPHP 2.10.0.2087 (php)

**Comment by andrei-epure-sonarsource** [comment]
hi - I'm afraid you are using quite old versions of SonarQube and the SonarC# analyzer - check the release page of this repository.

Another important aspect is the version of the Scanner for MSBuild you are using (I cannot see it here). Or the scanner-cli.

Please update to the latest supported version of SonarQube (SQ 7.9 LTS) and open a new ticket in case you encounter issues
