### ISSUE TITLE
Import of unit test reports for a mixed C# - VB.NET solution is failing

### ISSUE THREAD

**Issue by christophe-zurn-sonarsource** [SonarSource/sonar-dotnet#3109]
When trying to import unit test reports in a solution containing both C# and VB.NET code, the import will fail and stop the analysis.

**Steps to Reproduce:**
 1. Create a simple multi language solution with tests.
    Ex:
```
        /MySimpleSolution
            /MySimpleCSharpProj
                /Program.cs
            /MySimpleCSharpProj.Test
                /UnitTest1.cs
            /MySimpleVBNetProj
                /Program.vb
            /MySimpleVBNet.Test
                /UnitTest1.vb
```
 2. Start step of analysis with unit test parameters `/d:sonar.cs.nunit.reportsPaths=CSharpResult.xml` `/d:sonar.vbnet.nunit.reportsPaths=VBNetResult.xml`
 3. Build solution
 4. Run the unit tests and save the results (can be in the same or different reports, analysis will fail in both cases):
    `nunit3-console.exe .\MySimpleCSharpProj.Test\bin\Debug\net461\MySimpleCSharpProj.Test.dll --result CSharpResult.xml`
    `nunit3-console.exe .\MySimpleVBNet.Test\bin\Debug\net461\MySimpleVBNet.Test.dll --result VBNetResult.xml`
 5. Run end step of analysis => will fail with the following error:
```
java.lang.UnsupportedOperationException: Can not add the same measure twice on [key=CSharpVBNetUnitTests]: DefaultMeasure[component=[key=CSharpVBNetUnitTests],metric=Metric[id=<null>,key=tests,description=Number of unit tests,type=INT,direction=1,domain=Coverage,name=Unit Tests,qualitative=false,userManaged=false,enabled=true,worstValue=<null>,bestValue=<null>,optimizedBestValue=false,hidden=false,deleteHistoricalData=false,decimalScale=<null>],value=1,fromCore=false,storage=org.sonar.scanner.sensor.DefaultSensorStorage@176f7f3b,saved=false]
	at org.sonar.scanner.sensor.DefaultSensorStorage.saveMeasure(DefaultSensorStorage.java:177)
	at org.sonar.scanner.sensor.DefaultSensorStorage.store(DefaultSensorStorage.java:137)
	at org.sonar.api.batch.sensor.measure.internal.DefaultMeasure.doSave(DefaultMeasure.java:96)
	at org.sonar.api.batch.sensor.internal.DefaultStorable.save(DefaultStorable.java:45)
	at org.sonar.plugins.dotnet.tests.UnitTestResultsImportSensor.analyze(UnitTestResultsImportSensor.java:88)
	at org.sonar.plugins.dotnet.tests.UnitTestResultsImportSensor.execute(UnitTestResultsImportSensor.java:74)
	at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:48)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:85)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:62)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:82)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
```

**Context of failure:**
The `UnitTestResultsImportSensor` is trying to add global metrics (number of tests, number of test failures, test errors, ...) at the module level. Modules have been deprecated for a while now. So when both C# and VB.NET sensors try to register these metrics, they register it both at the project (fallback from modules) level. However, since we cannot register metrics on the same component (project in this case) more than once, the second sensor fails and crashes the analysis.
To avoid this issue, metrics should either be reported at the project level for all C# and VB.NET tests, or be reported on their corresponding folders.
Note that even if an exception is raised at this stage, this should not stop and fail the analysis, but merely report an error in the logs that test metrics could not be imported.

**Comment by santhonisz** [comment]
Hi there,

I'm assuming this issue is the same as the one we are encountering for our mixed C# and C++ solutions too. If we use the `sonar.cfamily.cppunit.reportsPath` for a mixed language solution then an exception such as the following is raised during analysis:
```
java.lang.UnsupportedOperationException: Can not add the same measure twice on [key=mixeddemo]: DefaultMeasure[component=[key=mixeddemo],metric=Metric[id=<null>,key=tests,description=Number of unit tests,type=INT,direction=1,domain=Coverage,name=Unit Tests,qualitative=false,userManaged=false,enabled=true,worstValue=<null>,bestValue=<null>,optimizedBestValue=false,hidden=false,deleteHistoricalData=false,decimalScale=<null>],value=32,fromCore=false]
        at org.sonar.scanner.sensor.DefaultSensorStorage.saveMeasure(DefaultSensorStorage.java:172)
        at org.sonar.scanner.sensor.DefaultSensorStorage.store(DefaultSensorStorage.java:132)
        at org.sonar.api.batch.sensor.measure.internal.DefaultMeasure.doSave(DefaultMeasure.java:95)
        at org.sonar.api.batch.sensor.internal.DefaultStorable.save(DefaultStorable.java:45)
        at com.sonar.cpp.plugin.cppunit.CppunitSensor.execute(CppunitSensor.java:61)
        at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:48)
        at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:85)
        at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1(ModuleSensorsExecutor.java:59)
        at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy(ModuleSensorsExecutor.java:77)
        at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:59)
        at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:82)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
        at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:400)
        at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:395)
        at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:392)
        at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:358)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
        at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:141)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
        at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:73)
        at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:67)
        at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
        at com.sun.proxy.$Proxy0.execute(Unknown Source)
        at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
        at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:112)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
        at org.sonarsource.scanner.cli.Main.main(Main.java:61)```

The work-around has been to prefix the `sonar.cfamily.cppunit.reportsPath` key with the project guid.

**Comment by costin-zaharia-sonarsource** [comment]
A bit more context about the issue:

As @christophe-zurn-sonarsource mentioned, modules were deprecated in the sonar api, and the metrics are now resolved at the project level. Since we can't register the same metric multiple times on the same project the import will fail. 

This has been addressed in other plugins ([Java](https://github.com/SonarSource/sonar-java/blob/ab10b6ecfaa502b96d314c66d0862714acbe400a/java-surefire/src/main/java/org/sonar/plugins/surefire/SurefireJavaParser.java#L177), [Go](https://github.com/SonarSource/sonar-go/blob/40d55921c7a63b67386a053490d17b6723a46cd5/sonar-go-plugin/src/main/java/org/sonar/go/plugin/GoTestSensor.java#L218), [PHP](https://github.com/SonarSource/sonar-php/blob/3875b7574ba3be9f2fb6ce21be815547b6f2642a/sonar-php-plugin/src/main/java/org/sonar/plugins/php/phpunit/TestFileReport.java#L61), ...) by registering the metrics per test file instead of project.

In order to do a proper fix, a possible solution is to change the importers for xUnit.Net, nUnit and VsTest to map the results to a file and not compute a summary per project.

Test report format specs: 
- xUnit.Net: https://xunit.net/docs/format-xml-v2
- nUnit: https://github.com/nunit/docs/wiki/Test-Result-XML-Format
- VsTest: https://docs.microsoft.com/en-us/visualstudio/test/vstest-console-options?view=vs-2019, https://github.com/microsoft/vstest-docs/blob/master/docs/report.md

Since this topic seems to deserve more attention I've created https://github.com/SonarSource/sonar-dotnet/issues/3259 to handle the rework of the importers and this issue will fix only the build failure.
