### ISSUE TITLE
Fix regression-test.ps1 when executed for single rule

### ISSUE THREAD

**Issue by pavel-mikula-sonarsource** [SonarSource/sonar-dotnet#4330]
Regression script fails when executed for a single rule to validate new changes and save time (analyzing all rules on all projects takes time)
```
regressino-test.ps1 -ruleId Sxxx

# Minimal reproducer, internal project verification causes the problem
regressino-test.ps1 -ruleId Sxxx -project ManuallyAddedNoncompliantIssues
```

>================================================
Processing analyzer results
================================================
Check differences for internal projects
You cannot call a method on a null-valued expression.
System.Management.Automation.RuntimeException: You cannot call a method on a null-valued expression.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.ScriptBlock.InvokeWithPipeImpl(ScriptBlockClauseToInvoke clauseToInvoke, Boolean createLocalScope, Dictionary`2 functionsToDefine, List`1 variablesToDefine, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Object[] args)
   at System.Management.Automation.ScriptBlock.<>c__DisplayClass57_0.<InvokeWithPipe>b__0()
   at System.Management.Automation.Runspaces.RunspaceBase.RunActionIfNoRunningPipelinesWithThreadCheck(Action action)
   at System.Management.Automation.ScriptBlock.InvokeWithPipe(Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Boolean propagateAllExceptionsToTop, List`1 variablesToDefine, Dictionary`2 functionsToDefine, Object[] args)
   at System.Management.Automation.ScriptBlock.DoInvokeReturnAsIs(Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Object[] args)
   at Microsoft.PowerShell.Commands.WhereObjectCommand.ProcessRecord()
   at System.Management.Automation.Cmdlet.DoProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
>   
>at <ScriptBlock>, C:\Projects\sonar-dotnet\analyzers\its\regression-test.ps1: line 348
at VerifyUnexpectedIssues, C:\Projects\sonar-dotnet\analyzers\its\regression-test.ps1: line 348
at CompareIssues, C:\Projects\sonar-dotnet\analyzers\its\regression-test.ps1: line 395
at CheckDiffsForInternalProject, C:\Projects\sonar-dotnet\analyzers\its\regression-test.ps1: line 428
at CheckInternalProjectsDifferences, C:\Projects\sonar-dotnet\analyzers\its\regression-test.ps1: line 442
at <ScriptBlock>, C:\Projects\sonar-dotnet\analyzers\its\regression-test.ps1: line 499
at <ScriptBlock>, <No file>: line 1

**Comment by pavel-mikula-sonarsource** [comment]
Script is also failing when there are 0 actual or expected issues (due to problem with a rule or issue simply not being present)
