### ISSUE TITLE
S2699 throws AD0001 when invoked via AnalyzerRunner.exe 

### ISSUE THREAD

**Issue by andrei-epure-sonarsource** [SonarSource/sonar-dotnet#4332]
happens (at least) for `nodatime`, `n2cms`, `efcore`

```
  AD0001: 16 instances
error AD0001: Analyzer 'SonarAnalyzer.Rules.CSharp.TestMethodShouldContainAssertion' threw an exception of type 'System.ArgumentException' with message 'SyntaxTree is not part of the compilation
Parameter name: syntaxTree'.
Exception occurred with following context:
Compilation: NodaTime.Test
SyntaxTree: C:\Workspace\external-projects\PERF_SUITE\projects\nodatime\src\NodaTime.Test\Globalization\NodaFormatInfoTest.cs
SyntaxNode: [Test] [TestCaseSource(typeof(Cultures ... [MethodDeclarationSyntax]@[756..967) (21,8)-(26,9)

System.ArgumentException: SyntaxTree is not part of the compilation
Parameter name: syntaxTree
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetSemanticModel(SyntaxTree syntaxTree, Boolean ignoreAccessibility) in C:\Workspace\external-projects\roslyn\src\Compilers\CSharp\Portable\Compilation\CSharpCompilation.cs:line 2147
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.CommonGetSemanticModel(SyntaxTree syntaxTree, Boolean ignoreAccessibility) in C:\Workspace\external-projects\roslyn\src\Compilers\CSharp\Portable\Compilation\CSharpCompilation.cs:line 3229
   at Microsoft.CodeAnalysis.Compilation.GetSemanticModel(SyntaxTree syntaxTree, Boolean ignoreAccessibility) in C:\Workspace\external-projects\roslyn\src\Compilers\Core\Portable\Compilation\Compilation.cs:line 211
   at SonarAnalyzer.Rules.CSharp.TestMethodShouldContainAssertion.ContainsAssertion(MethodDeclarationSyntax methodDeclaration, SemanticModel previousSemanticModel, ISet`1 visitedSymbols, Int32 level)
   at SonarAnalyzer.Rules.CSharp.TestMethodShouldContainAssertion.ContainsAssertion(MethodDeclarationSyntax methodDeclaration, SemanticModel previousSemanticModel, ISet`1 visitedSymbols, Int32 level)
   at SonarAnalyzer.Rules.CSharp.TestMethodShouldContainAssertion.<>c.<Initialize>b__11_0(SyntaxNodeAnalysisContext c)
   at SonarAnalyzer.Helpers.DiagnosticAnalyzerContextHelper.<>c__DisplayClass1_0`1.<RegisterSyntaxNodeActionInNonGenerated>b__0(SyntaxNodeAnalysisContext c)
   at SonarAnalyzer.Helpers.SonarAnalysisContext.<>c__DisplayClass46_0`1.<RegisterContextAction>b__0(TContext c)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__62`1.<ExecuteSyntaxNodeAction>b__62_0(ValueTuple`2 data) in C:\Workspace\external-projects\roslyn\src\Compilers\Core\Portable\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 918
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info) in C:\Workspace\external-projects\roslyn\src\Compilers\Core\Portable\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 1596
-----

Suppress the following diagnostics to disable this analyzer: S2699
```

**Comment by andrei-epure-sonarsource** [comment]
It fails on such a method:
```
        [Test]
        [TestCase("1000-01-01", "1000-01-02")]
        [TestCase("1000-01-01", "1000-02-01")]
        [TestCase("999-16-64", "1000-01-01")]
        [TestCase("-1-01-01", "-1-01-02")]
        [TestCase("-1-01-01", "-1-02-01")]
        [TestCase("-2-16-64", "-1-01-01")]
        [TestCase("-1-16-64", "0-01-01")]
        [TestCase("-1-16-64", "1-01-01")]
        public void Comparisons(string smallerText, string greaterText)
        {
            var smaller = YearMonthDay.Parse(smallerText);
            var greater = YearMonthDay.Parse(greaterText);
            TestHelper.TestCompareToStruct(smaller, smaller, greater);
            TestHelper.TestOperatorComparisonEquality(smaller, smaller, greater);
            TestHelper.TestEqualsStruct(smaller, smaller, greater);
        }
```

**Comment by andrei-epure-sonarsource** [comment]
as the stack trace says, `private static bool ContainsAssertion(MethodDeclarationSyntax methodDeclaration, SemanticModel previousSemanticModel, ISet<IMethodSymbol> visitedSymbols, int level)`

This happens during a recursive call:
```
   at Microsoft.CodeAnalysis.Compilation.GetSemanticModel(SyntaxTree syntaxTree, Boolean ignoreAccessibility) in C:\Workspace\external-projects\roslyn\src\Compilers\Core\Portable\Compilation\Compilation.cs:line 211
   at SonarAnalyzer.Rules.CSharp.TestMethodShouldContainAssertion.ContainsAssertion(MethodDeclarationSyntax methodDeclaration, SemanticModel previousSemanticModel, ISet`1 visitedSymbols, Int32 level)
   at SonarAnalyzer.Rules.CSharp.TestMethodShouldContainAssertion.ContainsAssertion(MethodDeclarationSyntax methodDeclaration, SemanticModel previousSemanticModel, ISet`1 visitedSymbols, Int32 level)
```

And the `GetSemanticModel` probably happens inside [EnsureCorrectSemanticModel](https://github.com/SonarSource/sonar-dotnet/blob/983b38f3efab045dd1f1f1f79960e169fe2ff8d6/analyzers/src/SonarAnalyzer.Common/Helpers/SyntaxNodeExtensions.cs#L27).

**Comment by andrei-epure-sonarsource** [comment]
This should be possible to repro by calling methods outside of the file - probably introduced in #4243

**Comment by andrei-epure-sonarsource** [comment]
Clarification: this only happens when being invoked with `AnalyzerRunner.exe`. It doesn't happen normally.
