### ISSUE TITLE
Fix AD0001 with Symbolic Execution engine

### ISSUE THREAD

**Issue by andrei-epure-sonarsource** [SonarSource/sonar-dotnet#4573]
This snippet leads to an uncaugth exception in the symbolic execution engine:

```
public class Reproducer
{
    private DateTime? foo;

    public virtual DateTime? Foo
    {
        get { return foo; }

        set
        {
            if (value.HasValue)
            {
                value = DateTime.SpecifyKind(value.Value, DateTimeKind.Unspecified);
            }

            if (foo != value || (foo.HasValue && value.HasValue && foo.Value.Kind != value.Value.Kind))
            {
                foo = value;
                Bar("x");
            }
        }
    }

    public void Bar(string x) { }
}
```

Stack trace:
```
 SonarAnalyzer.SymbolicExecution.SymbolicExecutionException: Error processing method: set_Foo ## Method file: ConditionEvaluatesToConstant.cs ## Method line: 2832,8 ## Inner exception: System.NotSupportedException: Unexpected constraint type: ObjectConstraint.Old constraints: NoValue ##    at SonarAnalyzer.SymbolicExecution.SymbolicValue.TrySetObjectConstraint(ObjectConstraint constraint, SymbolicValueConstraints oldConstraints, ProgramState programState) in C:\Workspace\sonar-dotnet\analyzers\src\SonarAnalyzer.CSharp\SymbolicExecution\Common\SymbolicValues\SymbolicValue.cs:line 177 ##    at SonarAnalyzer.SymbolicExecution.SymbolicValue.TrySetConstraint(SymbolicValueConstraint constraint, ProgramState programState) in C:\Workspace\sonar-dotnet\analyzers\src\SonarAnalyzer.CSharp\SymbolicExecution\Common\SymbolicValues\SymbolicValue.cs:line 84 ##    at SonarAnalyzer.Rules.CSharp.EmptyNullableValueAccess.HasValueAccessSymbolicValue.TrySetConstraint(SymbolicValueConstraint constraint, ProgramState programState) in C:\Workspace\sonar-dotnet\analyzers\src\SonarAnalyzer.CSharp\Rules\SymbolicExecution\EmptyNullableValueAccess.cs:line 152 ##    at SonarAnalyzer.SymbolicExecution.CSharpExplodedGraph.VisitBinaryBranch(BinaryBranchBlock binaryBranchBlock, ExplodedGraphNode node, SyntaxNode instruction) in C:\Workspace\sonar-dotnet\analyzers\src\SonarAnalyzer.CSharp\SymbolicExecution\CSharp\CSharpExplodedGraph.cs:line 870 ##    at SonarAnalyzer.SymbolicExecution.CSharpExplodedGraph.VisitBinaryBranch(BinaryBranchBlock binaryBranchBlock, ExplodedGraphNode node) in C:\Workspace\sonar-dotnet\analyzers\src\SonarAnalyzer.CSharp\SymbolicExecution\CSharp\CSharpExplodedGraph.cs:line 162 ##    at SonarAnalyzer.SymbolicExecution.AbstractExplodedGraph.Walk() in C:\Workspace\sonar-dotnet\analyzers\src\SonarAnalyzer.CSharp\SymbolicExecution\Common\AbstractExplodedGraph.cs:line 116 ##    at SonarAnalyzer.Rules.SymbolicExecution.SymbolicExecutionRunner.Analyze(CSharpExplodedGraph explodedGraph, SyntaxNodeAnalysisContext context) in C:\Workspace\sonar-dotnet\analyzers\src\SonarAnalyzer.CSharp\Rules\SymbolicExecution\SymbolicExecutionRunner.cs:line 62 ##    at SonarAnalyzer.Extensions.SonarAnalysisContextExtensions.Analyze(CSharpSyntaxNode declarationBody, ISymbol symbol, Action`2 runAnalysis, SyntaxNodeAnalysisContext context) in C:\Workspace\sonar-dotnet\analyzers\src\SonarAnalyzer.CSharp\Extensions\SonarAnalysisContextExtensions.cs:line 125 ##  ---> System.NotSupportedException: Unexpected constraint type: ObjectConstraint.Old constraints: NoValue
       at SonarAnalyzer.SymbolicExecution.SymbolicValue.TrySetObjectConstraint(ObjectConstraint constraint, SymbolicValueConstraints oldConstraints, ProgramState programState) in C:\Workspace\sonar-dotnet\analyzers\src\SonarAnalyzer.CSharp\SymbolicExecution\Common\SymbolicValues\SymbolicValue.cs:line 177
       at SonarAnalyzer.SymbolicExecution.SymbolicValue.TrySetConstraint(SymbolicValueConstraint constraint, ProgramState programState) in C:\Workspace\sonar-dotnet\analyzers\src\SonarAnalyzer.CSharp\SymbolicExecution\Common\SymbolicValues\SymbolicValue.cs:line 84
       at SonarAnalyzer.Rules.CSharp.EmptyNullableValueAccess.HasValueAccessSymbolicValue.TrySetConstraint(SymbolicValueConstraint constraint, ProgramState programState) in C:\Workspace\sonar-dotnet\analyzers\src\SonarAnalyzer.CSharp\Rules\SymbolicExecution\EmptyNullableValueAccess.cs:line 152
       at SonarAnalyzer.SymbolicExecution.CSharpExplodedGraph.VisitBinaryBranch(BinaryBranchBlock binaryBranchBlock, ExplodedGraphNode node, SyntaxNode instruction) in C:\Workspace\sonar-dotnet\analyzers\src\SonarAnalyzer.CSharp\SymbolicExecution\CSharp\CSharpExplodedGraph.cs:line 870
       at SonarAnalyzer.SymbolicExecution.CSharpExplodedGraph.VisitBinaryBranch(BinaryBranchBlock binaryBranchBlock, ExplodedGraphNode node) in C:\Workspace\sonar-dotnet\analyzers\src\SonarAnalyzer.CSharp\SymbolicExecution\CSharp\CSharpExplodedGraph.cs:line 162
       at SonarAnalyzer.SymbolicExecution.AbstractExplodedGraph.Walk() in C:\Workspace\sonar-dotnet\analyzers\src\SonarAnalyzer.CSharp\SymbolicExecution\Common\AbstractExplodedGraph.cs:line 116
       at SonarAnalyzer.Rules.SymbolicExecution.SymbolicExecutionRunner.Analyze(CSharpExplodedGraph explodedGraph, SyntaxNodeAnalysisContext context) in C:\Workspace\sonar-dotnet\analyzers\src\SonarAnalyzer.CSharp\Rules\SymbolicExecution\SymbolicExecutionRunner.cs:line 62
       at SonarAnalyzer.Extensions.SonarAnalysisContextExtensions.Analyze(CSharpSyntaxNode declarationBody, ISymbol symbol, Action`2 runAnalysis, SyntaxNodeAnalysisContext context) in C:\Workspace\sonar-dotnet\analyzers\src\SonarAnalyzer.CSharp\Extensions\SonarAnalysisContextExtensions.cs:line 125
       --- End of inner exception stack trace ---
       at SonarAnalyzer.Extensions.SonarAnalysisContextExtensions.Analyze(CSharpSyntaxNode declarationBody, ISymbol symbol, Action`2 runAnalysis, SyntaxNodeAnalysisContext context) in C:\Workspace\sonar-dotnet\analyzers\src\SonarAnalyzer.CSharp\Extensions\SonarAnalysisContextExtensions.cs:line 138
       at SonarAnalyzer.Extensions.SonarAnalysisContextExtensions.<>c__DisplayClass0_0.<RegisterExplodedGraphBasedAnalysis>b__2(SyntaxNodeAnalysisContext c) in C:\Workspace\sonar-dotnet\analyzers\src\SonarAnalyzer.CSharp\Extensions\SonarAnalysisContextExtensions.cs:line 82
       at SonarAnalyzer.Helpers.DiagnosticAnalyzerContextHelper.<>c__DisplayClass1_0`1.<RegisterSyntaxNodeActionInNonGenerated>b__0(SyntaxNodeAnalysisContext c) in C:\Workspace\sonar-dotnet\analyzers\src\SonarAnalyzer.Common\Helpers\DiagnosticAnalyzerContextHelper.cs:line 42
       at SonarAnalyzer.Helpers.SonarAnalysisContext.<>c__DisplayClass47_0`1.<RegisterContextAction>b__0(TContext c) in C:\Workspace\sonar-dotnet\analyzers\src\SonarAnalyzer.Common\Helpers\SonarAnalysisContext.cs:line 241
       at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__62`1.<ExecuteSyntaxNodeAction>b__62_0(ValueTuple`2 data)
       at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
    -----
    System.NotSupportedException: Unexpected constraint type: ObjectConstraint.Old constraints: NoValue
       at SonarAnalyzer.SymbolicExecution.SymbolicValue.TrySetObjectConstraint(ObjectConstraint constraint, SymbolicValueConstraints oldConstraints, ProgramState programState) in C:\Workspace\sonar-dotnet\analyzers\src\SonarAnalyzer.CSharp\SymbolicExecution\Common\SymbolicValues\SymbolicValue.cs:line 177
       at SonarAnalyzer.SymbolicExecution.SymbolicValue.TrySetConstraint(SymbolicValueConstraint constraint, ProgramState programState) in C:\Workspace\sonar-dotnet\analyzers\src\SonarAnalyzer.CSharp\SymbolicExecution\Common\SymbolicValues\SymbolicValue.cs:line 84
       at SonarAnalyzer.Rules.CSharp.EmptyNullableValueAccess.HasValueAccessSymbolicValue.TrySetConstraint(SymbolicValueConstraint constraint, ProgramState programState) in C:\Workspace\sonar-dotnet\analyzers\src\SonarAnalyzer.CSharp\Rules\SymbolicExecution\EmptyNullableValueAccess.cs:line 152
       at SonarAnalyzer.SymbolicExecution.CSharpExplodedGraph.VisitBinaryBranch(BinaryBranchBlock binaryBranchBlock, ExplodedGraphNode node, SyntaxNode instruction) in C:\Workspace\sonar-dotnet\analyzers\src\SonarAnalyzer.CSharp\SymbolicExecution\CSharp\CSharpExplodedGraph.cs:line 870
       at SonarAnalyzer.SymbolicExecution.CSharpExplodedGraph.VisitBinaryBranch(BinaryBranchBlock binaryBranchBlock, ExplodedGraphNode node) in C:\Workspace\sonar-dotnet\analyzers\src\SonarAnalyzer.CSharp\SymbolicExecution\CSharp\CSharpExplodedGraph.cs:line 162
       at SonarAnalyzer.SymbolicExecution.AbstractExplodedGraph.Walk() in C:\Workspace\sonar-dotnet\analyzers\src\SonarAnalyzer.CSharp\SymbolicExecution\Common\AbstractExplodedGraph.cs:line 116
       at SonarAnalyzer.Rules.SymbolicExecution.SymbolicExecutionRunner.Analyze(CSharpExplodedGraph explodedGraph, SyntaxNodeAnalysisContext context) in C:\Workspace\sonar-dotnet\analyzers\src\SonarAnalyzer.CSharp\Rules\SymbolicExecution\SymbolicExecutionRunner.cs:line 62
       at SonarAnalyzer.Extensions.SonarAnalysisContextExtensions.Analyze(CSharpSyntaxNode declarationBody, ISymbol symbol, Action`2 runAnalysis, SyntaxNodeAnalysisContext context) in C:\Workspace\sonar-dotnet\analyzers\src\SonarAnalyzer.CSharp\Extensions\SonarAnalysisContextExtensions.cs:line 125
    -----
```

**Comment by pavel-mikula-sonarsource** [comment]
Minimal:
```
ublic class Repro_4573
{
    private DateTime? foo;

    public virtual DateTime? Foo
    {
        get { return foo; }

        set
        {
            if (value.HasValue)
            {
                //HasValue and NoValue constraints are set here
            }
            if (foo != value || foo.HasValue) // NotNull clashes with NoValue
            {
                foo = value;
            }
        }
    }
}
```
