### ISSUE TITLE
Fix S3603 Bug and FN: NRE for local method with qualified attributes

### ISSUE THREAD

**Issue by rsking** [SonarSource/sonar-dotnet#5117]
### Description

When having a local function, with an attribute, PureAttributeOnVoidMethod  has a NullReferenceException.
`CSC : warning AD0001: Analyzer 'SonarAnalyzer.Rules.CSharp.PureAttributeOnVoidMethod' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.`

### Repro steps

``` csharp
namespace ClassLibrary1
{
    public static class Class1
    {
        public static void Function1()
        {
            DoSomething();

            [System.Diagnostics.CodeAnalysis.SuppressMessage("category", "checkId")]
            static void DoSomething()
            {
                // nothing to see here
            }
        }
    }
}
```

### Known workarounds

Use `pragma warning disable` if this is a `SuppressMessage`.

### Related information

* SonarAnalyzer.CSharp: 8.32.0.39516
* Visual Studio 2022
* dotnet sdk: 6.0.100
* Windows 11

**Comment by pavel-mikula-sonarsource** [comment]
Hi @rsking, 

I can't reproduce this issue. Can you create a small reproducer project that will link the analyzer as NuGet package to reproduce the AD0001 warning please?

**Comment by rsking** [comment]
[ClassLibrary1.zip](https://github.com/SonarSource/sonar-dotnet/files/7663390/ClassLibrary1.zip)
Small reproducer project uploaded. This consistently causes the issue with just `dotnet build` or `msbuild /t:Build`.

**Comment by rsking** [comment]
``` msbuild
Microsoft (R) Build Engine version 17.0.0+c9eb9dd64 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
CSC : warning AD0001: Analyzer 'SonarAnalyzer.Rules.CSharp.PureAttributeOnVoidMethod' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [C:\Users\rsking\source\scratch\ClassLibrary1\ClassLibrary1\ClassLibrary1.csproj]
  ClassLibrary1 -> C:\Users\rsking\source\scratch\ClassLibrary1\ClassLibrary1\bin\Debug\net6.0\ClassLibrary1.dll

Build succeeded.

CSC : warning AD0001: Analyzer 'SonarAnalyzer.Rules.CSharp.PureAttributeOnVoidMethod' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [C:\Users\rsking\source\scratch\ClassLibrary1\ClassLibrary1\ClassLibrary1.csproj]
    1 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.37
```

**Comment by pavel-mikula-sonarsource** [comment]
Thank you @rsking for the reproducer. I can reproduce it now!

```
        Exception occurred with following context:
         SyntaxNode: [System.Diagnostics.CodeAnalysis ... [LocalFunctionStatementSyntax]@[173..354) (9,12)-(13,13)
         System.NullReferenceException: Object reference not set to an instance of an object.
         at SonarAnalyzer.Rules.CSharp.PureAttributeOnVoidMethod.<>c.<Initialize>b__2_2(AttributeSyntax attribute)
         at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
         at SonarAnalyzer.Rules.CSharp.PureAttributeOnVoidMethod.<Initialize>b__2_0(SyntaxNodeAnalysisContext c)
         at SonarAnalyzer.Helpers.DiagnosticAnalyzerContextHelper.<>c__DisplayClass1_0`1.<RegisterSyntaxNodeActionInNonGenerated>b__0(SyntaxNodeAnalysisContext c)
         at SonarAnalyzer.Helpers.SonarAnalysisContext.<>c__DisplayClass47_0`1.<RegisterContextAction>b__0(TContext c)
         at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__62`1.<ExecuteSyntaxNodeAction>b__62_0(ValueTuple`2 data)
         at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
         -----
```
