### ISSUE TITLE
Incremental PR analysis fails for SQ < 9.4

### ISSUE THREAD

**Issue by costin-zaharia-sonarsource** [SonarSource/sonar-dotnet#6598]
### Description

When doing incremental PR analysis on a SonarQube version older than 9.4 the end step fails with:
```
java.lang.NoSuchMethodError: 'boolean org.sonar.api.batch.sensor.SensorContext.isCacheEnabled()'
	at org.sonarsource.dotnet.shared.plugins.AbstractFileCacheSensor.execute(AbstractFileCacheSensor.java:58)
	at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:48)
	at org.sonar.scanner.sensor.ProjectSensorsExecutor.execute(ProjectSensorsExecutor.java:49)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:361)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:141)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:73)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:67)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:112)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
```

The problem appears because the `isCacheEnabled` method was added in 9.4 and there is no backward compatibility support for this.

The impact of this issue should be very limited since the plugins are delivered as part of SonarQube and users are impacted only if are manually updating the plugin on an older version of SonarQube (<9.4).

**Comment by andrei-epure-sonarsource** [comment]
@costin-zaharia-sonarsource given that we don't support this scenario (users manually updating a plugin), should this ticket be closed?

From what I understand, running an analysis with the new Scanner on old SonarQube has no problem, it's only if users do un-supported actions on their instance (like updating a plugin), right?

**Comment by costin-zaharia-sonarsource** [comment]
I don't plan to include the fix in the LTS but I would still like to have this issue fixed in order to be consistent. 

Everywhere we use new APIs we check if they are available before using them and this avoids surprises when plugins are updated manually.

I think the decision to remove this checks should be discussed at the project level and if we decide that we don't need them, we should remove them all.

**Comment by andrei-epure-sonarsource** [comment]
sounds good!

**Comment by pavel-mikula-sonarsource** [comment]
IMO this adds support for an unsupported scenario = only adds technical debt that will need to be removed.

**Comment by pavel-mikula-sonarsource** [comment]
Is there a follow-up action somewhere? A few months from now, this one will be hard to spot and take a decision about.

**Comment by andrei-epure-sonarsource** [comment]
@pavel-mikula-sonarsource good point

I created a background task to specify a short sprint for removing all this logic (even if it is only deleting, it will still take time to do it and review it with care)


 https://trello.com/c/dPFIgfUj/721-evaluate-logic-for-unsupported-scenarios-of-using-sonarqube-and-specify-everywhere-it-needs-to-be-removed-from
