### ISSUE TITLE
Fix AD0001 in S1144: Implicit object creation inside collection expression

### ISSUE THREAD

**Issue by akurone** [SonarSource/sonar-dotnet#8024]
### Description
Hi,
I am currently migrating a lib project to .net 8 and I received an exception from `UnusedPrivateMember` analyzer.
Here is the AD0001 message:
```
Severity	Code	Description	Project	File	Line	Suppression State
Warning	AD0001	Analyzer 'SonarAnalyzer.Rules.CSharp.UnusedPrivateMember' threw an exception of type 'System.NullReferenceException' with the message 'Object reference not set to an instance of an object.'.
Exception occurred with the following context:
Compilation: SonarAnalyzerUnusedPrivateMemberNullReferenceException
ISymbol: Repro (NamedType)

System.NullReferenceException: Object reference not set to an instance of an object.
   at SonarAnalyzer.Wrappers.ObjectCreationFactory.ImplicitObjectCreation.TypeAsString(SemanticModel semanticModel)
   at SonarAnalyzer.Helpers.CSharpSymbolUsageCollector.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
   at SonarAnalyzer.Helpers.CSharpSymbolUsageCollector.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
   at SonarAnalyzer.Helpers.CSharpSymbolUsageCollector.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
   at SonarAnalyzer.Helpers.CSharpSymbolUsageCollector.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
   at SonarAnalyzer.Helpers.CSharpSymbolUsageCollector.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
   at SonarAnalyzer.Helpers.CSharpSymbolUsageCollector.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
   at SonarAnalyzer.Helpers.CSharpSymbolUsageCollector.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
   at SonarAnalyzer.Helpers.CSharpSymbolUsageCollector.Visit(SyntaxNode node)
   at SonarAnalyzer.Helpers.SafeCSharpSyntaxWalker.SafeVisit(SyntaxNode syntaxNode)
   at SonarAnalyzer.Rules.CSharp.UnusedPrivateMember.<>c__DisplayClass24_0.<VisitDeclaringReferences>b__1(SyntaxReference x)
   at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
   at SonarAnalyzer.Rules.CSharp.UnusedPrivateMember.NamedSymbolAction(SonarSymbolReportingContext context, HashSet`1 removableInternalTypes)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info, CancellationToken cancellationToken)
-----

Suppress the following diagnostics to disable this analyzer: S1144, S4487	SonarAnalyzerUnusedPrivateMemberNullReferenceException	D:\tmp\SonarAnalyzerUnusedPrivateMemberNullReferenceException\SonarAnalyzerUnusedPrivateMemberNullReferenceException.csproj	1	Active
```

#### Create a new console app using VS 2022 17.8.0 Preview 2.0. Add SonarAnalyzer.CSharp, .csproj would be like:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="SonarAnalyzer.CSharp" Version="9.10.0.77988">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
```

#### Add this file to the project:
```csharp
public sealed record Line(decimal Field);

public sealed class Repro
{
    public Line[] ThisCausesTheException() => ThisIsTheRootCause();

    private static Line[] ThisIsTheRootCause() => [new(0)];
}
```
#### Execute "Run Code Analysis on Solution" command:
![image](https://github.com/SonarSource/sonar-dotnet/assets/841676/089ee60d-3368-43ee-afea-fba5e653c78b)

### Known workarounds

Suppressing the mentioned analyzers (S1144, S4487) in exception message does **NOT** resolve the issue.

### Related information

* Visual Studio: **17.8.0 Preview 2.0**
* dotnet SDK: **8.0.100-rc.1.23455.8**
* SonarAnalyzer.CSharp: **9.10.0.77988**
* Operating System: **Win 11 22H2**

**Comment by zsolt-kolbay-sonarsource** [comment]
**Root cause:** `Microsoft.CodeAnalysis.SemanticModel.GetTypeInfo()` cannot resolve the given syntax node:
```cs
private static Line[] ThisIsTheRootCause() => [new(0)]; // Fails here: implicit object creation inside a collection literal (new in C# 12)
//                                            ^^^^^^^^
```

This results in `SonarAnalyzer.Wrappers.ObjectCreationFactory.TypeAsString()` throwing a `NullReferenceException`.
This isn't difficult to fix for the `UnusedPrivateMember` analyzer, but several other analyzers use the `SemanticModel.GetTypeInfo()` method. So it needs further investigation if other analyzers are affected as well.

**Comment by csaba-sagi-sonarsource** [comment]
Should be an issue on Roslyn`s side: https://github.com/dotnet/roslyn/issues/70041
